### PR TITLE
Update JQuery to v3.2.1

### PR DESCRIPTION
**Pull request by zwliew**
Update JQuery from v2.2.4 to v3.2.1. Also, get the script from a CDN.

### Submission Checklist

- [x] Your pull request targets the `master` branch of the repository.
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] You have read the [Contributing guidelines](https://github.com/jboss-outreach/gci/blob/master/CONTRIBUTING.md) and your changes follow them.

#### Type of Change

- [x] Bug fix
- [ ] New implementation

### PR Description

Update JQuery from v2.2.4 to v3.2.1. Also, get the script from a CDN.

Issue #98

### CODE REVIEW

**Comment by zwliew** [comment]
@aashutoshrathi are there any other changes you want to be made to this PR? the website's functions seem to be working fine for me on v3.2.1 of jquery

**Comment by zwliew** [comment]
@aashutoshrathi are there any other changes you want to be made to this PR? the website's functions seem to be working fine for me on v3.2.1 of jquery

**Comment by aashutoshrathi** [comment]
Resolve conflicts

**Comment by zwliew** [comment]
@aashutoshrathi any updates on this?

**Pull request merged**
