### PR TITLE
Update adding-student.md

### PR DESCRIPTION
**Pull request by dato2003**
### Submission Checklist

- [x] Your pull request targets the `master` branch of the repository.
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] You have read the [Contributing guidelines](https://github.com/jboss-outreach/gci/blob/master/CONTRIBUTING.md) and your changes follow them.

#### Type of Change

- [ ] Bug fix
- [x] New implementation

### PR Description

Issue #[Add issue number here.]

### CODE REVIEW

**Comment by garg-anuj** [comment]
@dato2003, Please refer https://github.com/jboss-outreach/gci/pull/60/files for what to be done.

_image should be 240x240_

**Comment by dato2003** [comment]
Changed

**Comment by dato2003** [comment]
Changed again this should be it

**Comment by garg-anuj** [comment]
You need to add yml file under _data/students

**Comment by dato2003** [comment]
Ohhh sorry thanks i will add it there

**Pull request closed without merging**
