### PR TITLE
Fetch Contributors from all repos

### PR DESCRIPTION
**Pull request by jatinluthra14**
This Pull will fetch all contributors for jboss-outreach organization.
There would be merge conflicts as the feature is already committed.
This is only for learning  and GCI Task [5231414834364416](https://codein.withgoogle.com/dashboard/task-instances/5231414834364416/)

### CODE REVIEW

**Comment by jatinluthra14** [comment]
@yashovardhanagrawal Conflicts will be there as it is already merged. It is only for GCI task

**Comment by yashovardhanagrawal** [comment]
thanks for informing

**Comment by jatinluthra14** [comment]
@yashovardhanagrawal Can you approve the task then?

**Comment by yashovardhanagrawal** [comment]
I would have reviewed it by today @jatinluthra14 

thanks to @aashutoshrathi it was done earlier only 😄

**Pull request closed without merging**
