### PR TITLE
Create BlazeFace.yml

### PR DESCRIPTION
**Pull request by BlazeFace**
### Submission Checklist

- [x] Your pull request targets the `master` branch of the repository.
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] You have read the [Contributing guidelines](https://github.com/jboss-outreach/gci/blob/master/CONTRIBUTING.md) and your changes follow them.

#### Type of Change

- [ ] Bug fix
- [x] New implementation

### PR Description

Issue #[Add issue number here.]

### CODE REVIEW

**Comment by garg-anuj** [comment]
@BlazeFace You will also need to add image of 244*244 to this pull request

**Comment by BlazeFace** [comment]
It wont let me upload a file

**Comment by garg-anuj** [comment]
@BlazeFace  what is the error?

**Comment by garg-anuj** [comment]
Please reopen when you start to work again on it

**Pull request closed without merging**
