### PR TITLE
Create sidhyatikku.yml profile

### PR DESCRIPTION
**Pull request by sidhyatikku**
### Submission Checklist

- [x] Your pull request targets the `master` branch of the repository.
- [ ] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] You have read the [Contributing guidelines](https://github.com/jboss-outreach/gci/blob/master/CONTRIBUTING.md) and your changes follow them.

#### Type of Change

- [x] Bug fix
- [x] New implementation

### PR Description

Issue #[Add issue number here.]

### CODE REVIEW

**Comment by sidhyatikku** [comment]
sidhya

**Comment by sidhyatikku** [comment]
I've uploaded my image

**Comment by lakhina** [comment]
@sidhyatikku  You have not uploaded the image

**Comment by sidhyatikku** [comment]
my image has been uploaded to images/students
@lakhina @m-murad

**Comment by lakhina** [comment]
@sidhyatikku  Push the commit to  your branch patch-1

**Pull request closed without merging**
