### PR TITLE
fixed broken link for blog

### PR DESCRIPTION
**Pull request by SachinRammoorthy**
### Submission Checklist

- [x] Your pull request targets the `master` branch of the repository.
- [ ] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] You have read the [Contributing guidelines](https://github.com/jboss-outreach/gci/blob/master/CONTRIBUTING.md) and your changes follow them.

#### Type of Change

- [x] Bug fix
- [x] New implementation

### PR Description

Issue #[Add issue number here.]

### CODE REVIEW

**Comment by garg-anuj** [comment]
@SachinRammoorthy some conflicts here

**Comment by SachinRammoorthy** [comment]
@garg-anuj resolved conflicts, but then it only shows contributions from this repo (gci). How do I get the contributors from all repos? I tried implementing several different forms, but none of them work...

**Comment by garg-anuj** [comment]
@SachinRammoorthy Hey we will not be able to review with this  amount of commit. Please squash them

**Comment by SachinRammoorthy** [comment]
@garg-anuj done.

**Comment by SachinRammoorthy** [comment]
@garg-anuj squashed commits and resolved conflicts, but then it only shows contributions from this repo (gci). How do I get the contributors from all repos? I tried implementing several different forms, but none of them work...

**Pull request merged**
