### PR TITLE
Update Projects Section

### PR DESCRIPTION
**Pull request by SachinRammoorthy**
### Submission Checklist

- [x] Your pull request targets the `master` branch of the repository.
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] You have read the [Contributing guidelines](https://github.com/jboss-outreach/gci/blob/master/CONTRIBUTING.md) and your changes follow them.

#### Type of Change

- [x] Bug fix
- [ ] New implementation

### PR Description

Previously, the Projects section showed a maximum of 30 contributors on all of the repos because the API call only got the contributors on the first page, which by default has 30 entries. This PR updates it to show 100 entries per page so the number of contributors shown is correct.

Issue #102

### CODE REVIEW

**Comment by SachinRammoorthy** [comment]
@aashutoshrathi any changes required?

**Comment by aashutoshrathi** [comment]
Will this help?

**Comment by SachinRammoorthy** [comment]
??

If you mean whether it will make a difference, yes because both the GCI website repo and another 2/3 more I think have way more than 30 contributors, but that is the maximum it shows right now...

**Comment by aashutoshrathi** [comment]
Okay

**Pull request merged**
