### PR TITLE
Projects Section

### PR DESCRIPTION
**Pull request by SachinRammoorthy**
## What's new?
 - Added more projects to the projects section. They are supposed to be projects with a `major` tag, but could not find any repos with such a tag. I filled the section with the most active projects.
- On hovering over each project, the number of contributors to that project is shown with the same animation as the contributors section.

Fixes Issue #19

### CODE REVIEW

**Comment by zwliew** [comment]
Should this data not be gotten straight from GitHub instead?

**Comment by aashutoshrathi** [comment]
Rebase and make an issue for it.

**Comment by SachinRammoorthy** [comment]
@aashutoshrathi issue already exists, as is mentioned in the description (#19 )

**Comment by aashutoshrathi** [comment]
Looks good but better if we can retrieve data and all projects

**Comment by SachinRammoorthy** [comment]
Shifted to #89

**Pull request closed without merging**
