### PR TITLE
Fixes: Footer CSS issues

### PR DESCRIPTION
**Pull request by SachinRammoorthy**
Issue #107 and #106 

Problem was that #90 (footer implementation) edited the `fa` class in `main.css` without specifying that it should be applied only to the footer, not all icons.

### CODE REVIEW

**Comment by divyanshkul** [comment]
Ahh bad mistake xD Probably because I made the footer separately and then combined it with the main site later.

**Comment by aashutoshrathi** [comment]
What is bad mistake?

**Comment by divyanshkul** [comment]
@aashutoshrathi the github logo in the contributors section (when you hover over individual profiles) gets shifted by a margin of 40px from the left. I forgot to add the additional (only to footer tag) in the css while working on the footer. 😏

**Comment by aashutoshrathi** [comment]
Yes, I noticed that but wasn't sure which PR caused that :smile: 
Also, will it be good practice to set a common picture for all projects?
Opinions @KeenWarrior ?

**Comment by SachinRammoorthy** [comment]
@aashutoshrathi am open to the idea, but I think that would look a little plain.

**Comment by divyanshkul** [comment]
@aashutoshrathi agreed, it would look better and more uniform.

**Comment by aashutoshrathi** [comment]
@SachinRammoorthy Change as per my comment

**Comment by SachinRammoorthy** [comment]
@aashutoshrathi done.

**Comment by aashutoshrathi** [comment]
No, @SachinRammoorthy you misinterpreted, I meant not to have same images for all. 😉

**Comment by SachinRammoorthy** [comment]
@aashutoshrathi the image is the same for all the projects... I think you may have confused the projects section with the contributor section 😉

**Comment by aashutoshrathi** [comment]
No.
I meant no to have same images for all **projects**

**Comment by SachinRammoorthy** [comment]
Yeah...that has already been done.

screen shot 2018-01-10 at 9 05 16 pm

**Comment by SachinRammoorthy** [comment]
@aashutoshrathi I am not sure if I am understanding right...just to be clear:
Is what I have done alright? Or should I revert back to the original where all the projects had different images?

**Comment by aashutoshrathi** [comment]
You should revert back to different images, one of the deployment showed me same images for all that's why I told you to revert 😅

**Comment by SachinRammoorthy** [comment]
Oh! I think I got confused by @divyanshkul's comment. 

`@aashutoshrathi agreed, it would look better and more uniform.`

THought I was supposed to give the same image.

I'll make the changes right away. 😆

**Comment by SachinRammoorthy** [comment]
@aashutoshrathi done. For projects that cannot be associated with an image (eg: issue-and-pr, junit-get-started), the RedHat logo is a placeholder.

screen shot 2018-01-10 at 9 20 14 pm

**Pull request merged**
