### PR TITLE
Populate contributors section with data from *all* repos

### PR DESCRIPTION
**Pull request by zwliew**
### Submission Checklist

- [x] Your pull request targets the `master` branch of the repository.
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] You have read the [Contributing guidelines](https://github.com/jboss-outreach/gci/blob/master/CONTRIBUTING.md) and your changes follow them.

#### Type of Change

- [x] Bug fix
- [x] New implementation

### PR Description
GCI task: https://codein.withgoogle.com/dashboard/task-instances/6465514631069696/

Previously, the contributors section was populated with data of contributors from solely the jboss-outreach/gci repo. Modify the code to load data from all repos under the jboss-outreach org.

**Possible future improvements:**
 * Add a loading indicator when the data is being populated
 * Reduce loading time (see below)

**Reducing loading time:**
*One way* to reduce this is to pre-process and pre-cache the data with a backend server that updates itself every few minutes or so. The client then simply queries the server for the ready data. This reduces the number of queries from several dozen to just one. Another benefit is it avoids the GitHub API rate limit.

If there are any other possibilities (maybe a more efficient implementation?), do inform me and I could look into them. I'm quite new to this and would love to know more :)

Issue #42

### CODE REVIEW

**Comment by zwliew** [comment]
To any mentor looking at this, could you have a look at #56 as well? Debugging with the console was painful without that commit.

**Comment by garg-anuj** [comment]
contributors are not populating in autodeploy. Please let me know if auto deploy is not displaying changes you made

**Comment by zwliew** [comment]
It works for me on Chrome Canary 65.0.3299.3, albeit a bit slow (~20 seconds to load as stated in the commit message). What browser and version are you using? Maybe some of the ECMAScript features being used here aren't yet implemented in the browser you're using.

**Comment by zwliew** [comment]
The prime culprit is probably the async functions. I'll try using Promises instead since it's an older feature.

**Comment by zwliew** [comment]
Hmm, actually, async functions were implemented in Chrome 55, which was about a year ago, so my previous idea seems unrelated.

**Comment by zwliew** [comment]
Another possibility is that you were being rate-limited. You can check whether that is true by checking if rate.remaining is 0 at https://api.github.com/rate_limit

**Comment by zwliew** [comment]
Ah I misunderstood the Javascript concurrency model. After reading up more on it, I realised that I can opt for a faster way of loading the data. Now, the loading time is ~5 seconds. Much more reasonable now.

**Pull request merged**
