### PR TITLE
Add new student

### PR DESCRIPTION
**Pull request by Hatollint**
### Submission Checklist

- [x] Your pull request targets the `master` branch of the repository.
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] You have read the [Contributing guidelines](https://github.com/jboss-outreach/gci/blob/master/CONTRIBUTING.md) and your changes follow them.

#### Type of Change

- [ ] Bug fix
- [x] New implementation

### PR Description

Add my photo and some information.

### CODE REVIEW

**Comment by Hatollint** [comment]
The inspector told me to add this

**Comment by Hatollint** [comment]
Im update yml file. Check it.

**Comment by lakhina** [comment]
@Hatollint Remove twitter link also

**Comment by Hatollint** [comment]
@lakhina Its okey?

**Pull request merged**
