### PR TITLE
Fetch contributor and project data from gci-server

### PR DESCRIPTION
**Pull request by zwliew**
### Submission Checklist

- [x] Your pull request targets the `master` branch of the repository.
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] You have read the [Contributing guidelines](https://github.com/jboss-outreach/gci/blob/master/CONTRIBUTING.md) and your changes follow them.

#### Type of Change

- [ ] Bug fix
- [x] New implementation

### PR Description

This PR aims to prevent users from hitting the GitHub API rate limit (see: #96).

Since it isn't very feasible to get the user to authenticate on the GCI website, we instead use a separate server to poll the GitHub API every 30 minutes. This way, the GCI website can query the API endpoints on our own server (gci-server) as often as it needs to.

Changes:
 * Fetch contributor and project data from gci-server
 * Clean up some code
 * Use JQuery for DOM manipulation
 * Address an error caused by referencing a non-existent image

GitHub repository for the gci-server repo: https://github.com/zwliew/gci-server

Issue #96

### CODE REVIEW

**Comment by zwliew** [comment]
https://gci-server.herokuapp.com is currently running under my Heroku account. If this seems fine, the the [gci-server](https://github.com/zwliew/gci-server) repository should probably be forked and the server should be deployed by one of the admins/mentors.

**Comment by zwliew** [comment]
This PR should be ready now.

**Comment by aashutoshrathi** [comment]
Don't we already have it?

**Comment by zwliew** [comment]
What do we already have?

**Comment by aashutoshrathi** [comment]
Okay, resolve conflicts, I'll review it again.

**Comment by aashutoshrathi** [comment]
> This PR aims to fetch that data from a [different source](https://github.com/zwliew/gci-server), instead of fetching from GitHub's API. By doing so, we circumvent the [limitations](https://github.com/jboss-outreach/gci/issues/96) that GitHub's API poses.
  
Actually, we are storing the data on another server, which is same as now. 😕

**Comment by zwliew** [comment]
The difference is that the other server polls for new data every 30 min, and doesn't have a rate limit.

**Comment by aashutoshrathi** [comment]
Okay, but its deployed on your Heroku app, better if we move it on some mentor's or Anuj's Heroku? Right?

**Comment by zwliew** [comment]
Yeah, I mentioned that in a comment above (probably hidden by the many auto-deploy messages by now :P)

**Comment by zwliew** [comment]
@KeenWarrior when you get the chance, could you have another look at this?

**Comment by KeenWarrior** [comment]
@zwliew yup it's nice work. will take deeper look in few hours. remind me if i forget

**Comment by zwliew** [comment]
Thanks; since this isn't a GCI task, I'm good with waiting until you're free for review.

**Comment by zwliew** [comment]
@KeenWarrior any updates on this?

**Pull request closed without merging**
