### PR TITLE
Improvements to the Profile Card

### LINKED ISSUE #77: Improvements to the Profile Card
- `Information of` text from the card can be removed, it is redundant and ugly.
- Social media Icon can also be added to the card, as per link given or not.
- A bit of transparency on card won't hurt.
- Cards edges should be a little round.
- In some cases, picture and text are getting mixed, so margins can be improved.

This issue is open to more suggestion, comment below to let the issue taker know.

### PR DESCRIPTION
**Pull request by SachinRammoorthy**
Fixes #77 

Also made a minor improvement to the contributor section (alignment).

Not sure why Travis is failing. There are no details on the page, and it works perfectly for me.

### CODE REVIEW

**Comment by aashutoshrathi** [comment]
Looks good, there is some problem with Harpreet Singh's picture and also some descriptions are too close to pictures, fix them

**Comment by SachinRammoorthy** [comment]
@aashutoshrathi have updated the PR.

**Comment by SachinRammoorthy** [comment]
Forgot about student section 😅

**Comment by aashutoshrathi** [comment]
Just leave Travis for a while it will fix soon.

**Comment by SachinRammoorthy** [comment]
Is it OK if number of contributors shows inside the popup?

**Comment by aashutoshrathi** [comment]
Yes it is, but will be more than okay if it shows on hover like contributions for contributors 😄

**Comment by SachinRammoorthy** [comment]
@aashutoshrathi took some time, but got it to work! Please have a look.

**Comment by aashutoshrathi** [comment]
Please do one more commit and don't squash, so that I can check deploy.

**Pull request merged**
