### PR TITLE
Fixed scrolling issue

### PR DESCRIPTION
**Pull request by SachinRammoorthy**
### Submission Checklist

- [x] Your pull request targets the `master` branch of the repository.
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] You have read the [Contributing guidelines](https://github.com/jboss-outreach/gci/blob/master/CONTRIBUTING.md) and your changes follow them.

#### Type of Change

- [x] Bug fix

### PR Description

Fixed minor issues in scrolling, menu. Contributor & issues section wasn't highlighted before.
Issue #70 , #46 & partly #73

### CODE REVIEW

**Comment by aashutoshrathi** [comment]
There are still issue with contributor's tag highlighting in this, @SachinRammoorthy #74 did it better, take a look

**Comment by SachinRammoorthy** [comment]
@aashutoshrathi I cannot see any issue with the contributors tag here. In #74 , the contributors tag is not highlighted for the majority of the section...that was the fix of this PR.

**Comment by aashutoshrathi** [comment]
Yes, but that look is better 😅

**Comment by SachinRammoorthy** [comment]
@aashutoshrathi Made some changes. Is it better now?

**Comment by aashutoshrathi** [comment]
Contributors tag still can't highlight, some things are buggy out there.

**Comment by divyanshkul** [comment]
Hey @aashutoshrathi @SachinRammoorthy fixed the issues raised here in https://github.com/jboss-outreach/gci/pull/74 do have a look

**Pull request merged**
