### PR TITLE
Add ParthRPurohit Files

### PR DESCRIPTION
**Pull request by ParthRPurohit**
Adding ParthRPurohit to the students folder

### Submission Checklist

- [x] Your pull request targets the `master` branch of the repository.
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] You have read the [Contributing guidelines](https://github.com/jboss-outreach/gci/blob/master/CONTRIBUTING.md) and your changes follow them.

#### Type of Change

- [ ] Bug fix
- [x] New implementation

### PR Description

Issue #[108]

### CODE REVIEW

**Comment by ParthRPurohit** [comment]
parthpurohit-min

**Comment by ParthRPurohit** [comment]
Awesome! I hope this worked better, I cloned the repository, opened it in Github Desktop, made the changes, and clicked "Commit to master". It did so successfully, so I hope it worked, despite that I don't know how to check it's success.

(I also added the picture here if that helps in the process 😄 )

Thanks so much for your help -- I'm pretty new to the world of coding, but I'm really excited to learn more!

**Comment by yashovardhanagrawal** [comment]
did you push it to the specific branch, ie `patch-2` also, because in the commit there is no mention of your picture...

posting in the comment section doesn't help here 😛 

so if you're using github desktop fine.. at the top there must be written your branch, ie. master change that to `patch-2` and then add you photo to the specific folder again, and commit to patch-2 then on the top click push 1 commit

**Comment by ParthRPurohit** [comment]
Aha! I think I figured it out finally! Thanks for your help!

I made it into new pull request (#114 ). Thanks again for everything -- I can't wait to get back to more tasks!

**Comment by yashovardhanagrawal** [comment]
why are you making new pull requests everytime? 😕 

do one thing.. learn git first.. from next time don't make new PRs everytime its a hassle totally

**Comment by yashovardhanagrawal** [comment]
anyway I am closing this.. keep in mind what I said from the next time

**Pull request closed without merging**
