### PR TITLE
Address some Codacy issues

### PR DESCRIPTION
**Pull request by zwliew**
### Submission Checklist

- [x] Your pull request targets the `master` branch of the repository.
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] You have read the [Contributing guidelines](https://github.com/jboss-outreach/gci/blob/master/CONTRIBUTING.md) and your changes follow them.

#### Type of Change

 - [x] Code quality improvements

### PR Description
Address a few of the issues found by Codacy. View the commit message for more info on the issues.
GCI task: https://codein.withgoogle.com/tasks/5561057131102208

Issue #50

### CODE REVIEW

**Comment by zwliew** [comment]
Codacy reports that there is +1 issue, but that issue has always been there. It was merely being masked by another issue in the same line of code.

**Comment by zwliew** [comment]
The Codacy failure has been resolved. Is this good to merge?

**Comment by aashutoshrathi** [comment]
@zwliew are you working on it?

**Comment by zwliew** [comment]
Actually there isn't much point to this PR now that most of the code has been removed in commit 2e2baac6b537834ed1f90dca028f94bb3922d4fb

**Comment by zwliew** [comment]
Closing this since the PR isn't very useful anymore.

**Pull request closed without merging**
